apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ .Values.serviceName }}-backend
spec:
  securityPolicy:
    name: {{ .Values.cloudarmorName }}
  iap:
    enabled: true
    oauthclientCredentials:
      secretName: {{ .Values.iapName }}