apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/backend-config: '{"default": "{{ .Values.serviceName }}-backend"}'
  name: {{.Values.serviceName}}
  labels:
    {{- range $key, $value := .Values.labels }}
    {{$key}}: {{$value}}
    {{- end}}
spec:
  ports:
#    {{- range $index, $ports := .Values.servicePorts -}}
#    {{- end }}
  - port: {{ .Values.servicePorts.port }}
    name: {{ .Values.servicePorts.name }}
  selector:
    {{- range $key, $value := .Values.labels }}
    {{$key}}: {{$value}}
    {{- end}}
  type: {{.Values.serviceType}}
