apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: my-backendconfig
spec:
  securityPolicy:
    name: "only-trusted"
  iap:
    enabled: true
    oauthclientCredentials:
      secretName: devendra-oauth-iap