apiVersion: v1
entries:
  nginx_chart:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-02-23T07:57:46.42968-08:00"
    description: A Helm chart for Kubernetes
    digest: bacff4e3f91dda1c50559dd0c67f6f0344d61084efb8700810598bc1e9ae6149
    name: nginx_chart
    type: application
    urls:
    - nginx_chart-0.1.0.tgz
    version: 0.1.0
generated: "2021-02-23T07:57:46.428833-08:00"
